In [10]:
import sys
!{sys.executable} -m pip install snowflake-connector-python

Requirement already satisfied: snowflake-connector-python in c:\users\2025a.laptop\anaconda3\lib\site-packages (4.7.3)
Requirement already satisfied: asn1crypto<2.0.0,>0.24.0 in c:\users\2025a.laptop\anaconda3\lib\site-packages (from snowflake-connector-python) (1.5.1)
Requirement already satisfied: cryptography>=46.0.5 in c:\users\2025a.laptop\anaconda3\lib\site-packages (from snowflake-connector-python) (46.0.7)
Requirement already satisfied: pyOpenSSL>=24.0.0 in c:\users\2025a.laptop\anaconda3\lib\site-packages (from snowflake-connector-python) (25.3.0)
Requirement already satisfied: pyjwt<3.0.0,>=2.10.1 in c:\users\2025a.laptop\anaconda3\lib\site-packages (from snowflake-connector-python) (2.10.1)
Requirement already satisfied: pytz in c:\users\2025a.laptop\anaconda3\lib\site-packages (from snowflake-connector-python) (2025.2)
Requirement already satisfied: requests<3.0.0,>=2.32.4 in c:\users\2025a.laptop\anaconda3\lib\site-packages (from snowflake-connector-python) (2.32.5)
Requirement already satisfied: packaging in c:\users\2025a.laptop\anaconda3\lib\site-packages (from snowflake-connector-python) (25.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\2025a.laptop\anaconda3\lib\site-packages (from snowflake-connector-python) (3.4.4)
Requirement already satisfied: idna<4,>=3.7 in c:\users\2025a.laptop\anaconda3\lib\site-packages (from snowflake-connector-python) (3.11)
Requirement already satisfied: certifi>=2024.7.4 in c:\users\2025a.laptop\anaconda3\lib\site-packages (from snowflake-connector-python) (2025.11.12)
Requirement already satisfied: typing_extensions<5,>=4.3 in c:\users\2025a.laptop\anaconda3\lib\site-packages (from snowflake-connector-python) (4.15.0)
Requirement already satisfied: filelock<4,>=3.5 in c:\users\2025a.laptop\anaconda3\lib\site-packages (from snowflake-connector-python) (3.20.0)
Requirement already satisfied: sortedcontainers>=2.4.0 in c:\users\2025a.laptop\anaconda3\lib\site-packages (from snowflake-connector-python) (2.4.0)
Requirement already satisfied: platformdirs<5.0.0,>=2.6.0 in c:\users\2025a.laptop\anaconda3\lib\site-packages (from snowflake-connector-python) (4.5.0)
Requirement already satisfied: tomlkit in c:\users\2025a.laptop\anaconda3\lib\site-packages (from snowflake-connector-python) (0.13.3)
Requirement already satisfied: boto3>=1.24 in c:\users\2025a.laptop\anaconda3\lib\site-packages (from snowflake-connector-python) (1.43.91)
Requirement already satisfied: botocore>=1.24 in c:\users\2025a.laptop\anaconda3\lib\site-packages (from snowflake-connector-python) (1.43.91)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\2025a.laptop\anaconda3\lib\site-packages (from requests<3.0.0,>=2.32.4->snowflake-connector-python) (2.5.0)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\2025a.laptop\anaconda3\lib\site-packages (from boto3>=1.24->snowflake-connector-python) (1.0.1)
Requirement already satisfied: s3transfer<0.20.0,>=0.19.0 in c:\users\2025a.laptop\anaconda3\lib\site-packages (from boto3>=1.24->snowflake-connector-python) (0.19.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\2025a.laptop\anaconda3\lib\site-packages (from botocore>=1.24->snowflake-connector-python) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\2025a.laptop\anaconda3\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore>=1.24->snowflake-connector-python) (1.17.0)
Requirement already satisfied: cffi>=2.0.0 in c:\users\2025a.laptop\anaconda3\lib\site-packages (from cryptography>=46.0.5->snowflake-connector-python) (2.0.0)
Requirement already satisfied: pycparser in c:\users\2025a.laptop\anaconda3\lib\site-packages (from cffi>=2.0.0->cryptography>=46.0.5->snowflake-connector-python) (2.23)

In [15]:
import snowflake.connector

In [16]:
from snowflake.connector.pandas_tools import write_pandas

In [17]:
import pandas as pd

In [18]:
fact_transactions = pd.read_excel('All_Transactions.xlsx')

In [20]:
dim_users = pd.read_excel('All_Users.xlsx')

In [21]:
fact_transactions.head()

,Transaction_ID,Amount,User_ID,Service,Service Type,Payment_Status,Reason,Date
0,RCG_0C338474B366,926.59,PP0021371,Recharge_Bills,FASTag Recharge,Successful,Successful,2024-06-09
1,RCG_6B3B86B07A76,1211.64,PP0002388,Recharge_Bills,DTH,Successful,Successful,2024-08-04
2,RCG_767822392A0E,746.27,PP1101831,Recharge_Bills,Cable TV,Successful,Successful,2024-02-19
3,RCG_527E6AC74B11,1319.89,PP0033099,Recharge_Bills,Mobile Recharge,Successful,Successful,2024-12-22
4,RCG_6B50A8C694E1,112.44,PP1059869,Recharge_Bills,Cable TV,Successful,Successful,2024-09-07

In [22]:
dim_users.head()

     User_ID             Name  Age  Join_Date
0  PP0000001     Holly Rivera   56 2025-06-17
1  PP0000002      Kevin Lopez   46 2023-12-10
2  PP0000003  Douglas Roberts   32 2024-09-14
3  PP0000004    Walter Davila   60 2023-10-19
4  PP0000005      Grace Blake   25 2025-03-10

In [23]:
conn = snowflake.connector.connect(
    user="HARSHND",
    password="Harsh@@5757260",
    account="cm80021.ap-southeast-7.aws",
    warehouse="COMPUTE_WH",
    role="ACCOUNTADMIN"
)

cs = conn.cursor()
cs.execute("SELECT CURRENT_VERSION()")
print("Conneccted:", cs.fetchone())

Conneccted: ('10.32.102',)

In [24]:
cs.execute("CREATE DATABASE IF NOT EXISTS PHONEPE_ANALYTICS")
cs.execute("CREATE SCHEMA IF NOT EXISTS PHONEPE_ANALYTICS.PUBLIC")
print("Database and schema created")
cs.close()
conn.close()

Database and schema created

In [25]:
conn = snowflake.connector.connect(
    user="HARSHND",
    password="Harsh@@5757260",
    account="cm80021.ap-southeast-7.aws",
    warehouse="COMPUTE_WH",
    database="PHONEPE_ANALYTICS",
    schema="PUBLIC",
    role="ACCOUNTADMIN"
)
print("Connected with database and schema set.")

Connected with database and schema set.

In [26]:
fact_transactions.columns = [c.upper() for c in fact_transactions.columns]
dim_users.columns = [c.upper() for c in dim_users.columns]

# Loading fact_transaction data
success, nchunk, nrows, _ = write_pandas(
    conn, fact_transactions, "FACT_TRANSACTIONS",
    auto_create_table=True, overwrite=True
)

# Loading dim_users data
success, nchunk, nrows, _ = write_pandas(
    conn, dim_users, "DIM_USERS",
    auto_create_table=True, overwrite=True
)

conn.close()